const express  = require('express');
const CalEvent = require('../models/other-models').CalEvent;
const { protect } = require('../middleware/auth');
const router   = express.Router();
router.use(protect);
router.get('/',     async (req,res) => { try { const d=await CalEvent.find().sort({date:1}); res.json({success:true,data:d}); } catch(e){res.status(500).json({success:false,message:e.message});} });
router.post('/',    async (req,res) => { try { const d=await CalEvent.create({...req.body,createdBy:req.user._id}); res.status(201).json({success:true,data:d}); } catch(e){res.status(400).json({success:false,message:e.message});} });
router.put('/:id',  async (req,res) => { try { const d=await CalEvent.findByIdAndUpdate(req.params.id,req.body,{new:true}); res.json({success:true,data:d}); } catch(e){res.status(400).json({success:false,message:e.message});} });
router.delete('/:id',async(req,res) => { try { await CalEvent.findByIdAndDelete(req.params.id); res.json({success:true}); } catch(e){res.status(500).json({success:false,message:e.message});} });
module.exports = router;
